#page title
page_title                                : Hello There - Greeting Cards                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1632485298                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Hello There - Greeting Cards                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Coming this fall                                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Do you hate throwing away greeting cards, but hate keeping them too?

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : rakTech, LLC                               
your_link                                 : https://raktech.app                     
your_city                                 : the USA                                
email_address                             : raktech_dev@icloud.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : hellothere_app
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Greeting cards, meet iOS
    description                           : Catalog and inventory cards from friends and family
    fontawesome_icon_name                 : mobile
    
  - title                                 : Essential
    description                           : Never feel bad for tossing another greeting card
    fontawesome_icon_name                 : check
    
  - title                                 : Widgets
    description                           : Feature cards on your homescreen, and stats on your lock screen
    fontawesome_icon_name                 : images

  - title                                 : Privacy
    description                           : No personally identifiable information is ever collected
    fontawesome_icon_name                 : lock

  - title                                 : iCloud
    description                           : Folders and cards are automatically synced and backed up to iCloud (Pro)
    fontawesome_icon_name                 : cloud

  - title                                 : Security
    description                           : Lock your app with biometric authentication (Pro)
    fontawesome_icon_name                 : fingerprint
  
  - title                                 : Favorites
    description                           : Some cards deserve more attention -- easily find your favorites
    fontawesome_icon_name                 : star

  - title                                 : Apple exclusive
    description                           : Designed exclusively for iPhone and iPad
    fontawesome_icon_name                 : heart

  - title                                 : iOS 16
    description                           : Built natively using the latest APIs
    fontawesome_icon_name                 : cogs

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.

# Press Review List                       Edit, add or remove press reviews to be presented.
pressreviews                              :

  - author                                : @joshdholtz
    quote                                 : I hate throwing away cards, but also hate keeping them, so this is great!
    sitename                              : 
    siteurl                               : 
    fontawesome_icon_name                 : newspaper
    
  - author                                : @jmarcus93
    quote                                 : This is one of the best ideas I’ve seen in a long time! ...Clean interface and fixes a problem for me personally! Amazing.
    sitename                              : Twitter
    siteurl                               : https://twitter.com/JMarcus93/status/1551872541303635968
    fontawesome_icon_name                 : newspaper
    
  - author                                : @t87
    quote                                 : That’s a wonderful idea, I love it!
    sitename                              : Twitter
    siteurl                               : https://twitter.com/t87/status/1550275112041332736 
    fontawesome_icon_name                 : newspaper
    

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#00a4ed"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#00a4ed"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
